### PR TITLE
feat: implement disk wiping via several methods

### PR DESCRIPTION
**Pull request by smira**
Methods are tried until one of them succeeds, starting with the most
preferred one.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
I have a bug here, hold on...

**Comment by Ulexus** [comment]
Th implementation seems to be empty; intentional?

**Comment by smira** [comment]
> Th implementation seems to be empty; intentional?

It's only for darwin, it has just stubs, linux implementation is real

**Review by Ulexus — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]
It feels a little weird to return a string that specifies the method used, but I don't know if I have any better ideas. Nothing to block on, but wondering if we could discover the capabilities for the block device, then leave it up to the user to decide which method to use explicitly. Something for the future.

**Comment by smira** [comment]
> It feels a little weird to return a string that specifies the method used, but I don't know if I have any better ideas. Nothing to block on, but wondering if we could discover the capabilities for the block device, then leave it up to the user to decide which method to use explicitly. Something for the future.

we could add a way to enforce the method in the future (probably only makes sense to enforce `secdiscard`, as everything else is writing zeroes, and the difference is time it takes to wipe.

I started that while doing local tests for `Zero` with Talos installer, and with `/dev/loopX` device backed by sparse file (4 GiB), zeroing out via `/dev/zero` takes ~15 seconds, while `BLKZEROOUT` (/dev/loop doesn't support anything else) takes less than a second. It's a huge difference even for such usecase.

**Pull request merged**
