### PR TITLE
fix: add missing file xfs.go

### PR DESCRIPTION
**Pull request by smira**
Not sure why it got missed.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Comment by smira** [comment]
I understand what's going on, I'll work through it next week

**Comment by andrewrynhard** [comment]
> Not sure why it got missed.
> 
> Signed-off-by: Andrey Smirnov [smirnov.andrey@gmail.com](mailto:smirnov.andrey@gmail.com)

I dropped this because I didn't like the fact that it shells out to mkfs. I was hoping to keep that specific to talos, and keep this library more pure. I'm not gonna die on a hill over it, but that was my original thinking.

**Comment by smira** [comment]
yep, thanks, Andrew, I now got it. I will refactor things and keep those functions in Talos repo

**Comment by andrewrynhard** [comment]
> yep, thanks, Andrew, I now got it. I will refactor things and keep those functions in Talos repo

If you have a need for this, then I don't think it's a big deal to bring it in. Up to you. I was just giving you the background 🙂.

**Pull request closed without merging**
